// Generated by xplatter v0.1.1-8-gf34891c on 2026-02-19 00:02:08 PST.
// DO NOT EDIT — this file is regenerated each time xplatter runs.

use std::ffi::c_void;
use crate::hello_xplatter_types::*;

/// Lifecycle interface methods.
pub trait Lifecycle {
    fn create_greeter(&self) -> Result<*mut c_void, HelloErrorCode>;
    fn destroy_greeter(&self, greeter: *mut c_void);
}

/// Greeter interface methods.
pub trait Greeter {
    fn say_hello(&self, greeter: *mut c_void, name: &str) -> Result<HelloGreeting, HelloErrorCode>;
}

