// Generated by xplatter v0.1.1-8-gf34891c on 2026-02-19 00:02:08 PST.
// DO NOT EDIT — this file is regenerated each time xplatter runs.

use std::os::raw::c_char;

#[repr(i32)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum HelloErrorCode {
    Ok = 0,
    InvalidArgument = 1,
    InternalError = 2,
}

#[repr(C)]
#[derive(Debug)]
pub struct HelloGreeting {
    pub message: *const c_char,
    pub apiImpl: *const c_char,
}

