// Generated by xplatter v0.1.1-8-gf34891c on 2026-02-19 00:02:08 PST.
// DO NOT EDIT — this file is regenerated each time xplatter runs.

use std::ffi::{c_void, CStr};
use std::os::raw::c_char;
use crate::hello_xplatter_types::*;
use crate::hello_xplatter_trait::*;
use crate::hello_xplatter_impl::*;

// lifecycle
#[no_mangle]
pub unsafe extern "C" fn hello_xplatter_lifecycle_create_greeter(out_result: *mut *mut c_void) -> i32 {
    match Lifecycle::create_greeter(&Impl) {
        Ok(val) => {
            *out_result = val;
            0
        }
        Err(e) => e as i32,
    }
}

#[no_mangle]
pub unsafe extern "C" fn hello_xplatter_lifecycle_destroy_greeter(greeter: *mut c_void) {
    Lifecycle::destroy_greeter(&Impl, greeter);
}

// greeter
#[no_mangle]
pub unsafe extern "C" fn hello_xplatter_greeter_say_hello(greeter: *mut c_void, name: *const c_char, out_result: *mut HelloGreeting) -> i32 {
    let name = CStr::from_ptr(name).to_str().expect("invalid UTF-8");
    match Greeter::say_hello(&Impl, greeter, name) {
        Ok(val) => {
            *out_result = val;
            0
        }
        Err(e) => e as i32,
    }
}

