// Generated by xplatter dev on 2026-02-19 03:04:41 PST.
// This is a scaffold — customize as needed. Regeneration will not overwrite this file.

#[path = "../generated/hello_xplatter_types.rs"]
pub mod hello_xplatter_types;
#[path = "../generated/hello_xplatter_trait.rs"]
pub mod hello_xplatter_trait;
#[path = "../generated/hello_xplatter_ffi.rs"]
pub mod hello_xplatter_ffi;
pub mod hello_xplatter_impl;
pub mod platform_services;

#[cfg(target_arch = "wasm32")]
mod wasm_alloc;
