// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_HELLOTYPES_HELLO_H_
#define FLATBUFFERS_GENERATED_HELLOTYPES_HELLO_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace Hello {

struct Greeting;
struct GreetingBuilder;

enum ErrorCode : int32_t {
  ErrorCode_Ok = 0,
  ErrorCode_InvalidArgument = 1,
  ErrorCode_InternalError = 2,
  ErrorCode_MIN = ErrorCode_Ok,
  ErrorCode_MAX = ErrorCode_InternalError
};

inline const ErrorCode (&EnumValuesErrorCode())[3] {
  static const ErrorCode values[] = {
    ErrorCode_Ok,
    ErrorCode_InvalidArgument,
    ErrorCode_InternalError
  };
  return values;
}

inline const char * const *EnumNamesErrorCode() {
  static const char * const names[4] = {
    "Ok",
    "InvalidArgument",
    "InternalError",
    nullptr
  };
  return names;
}

inline const char *EnumNameErrorCode(ErrorCode e) {
  if (::flatbuffers::IsOutRange(e, ErrorCode_Ok, ErrorCode_InternalError)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesErrorCode()[index];
}

struct Greeting FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef GreetingBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_MESSAGE = 4,
    VT_APIIMPL = 6
  };
  const ::flatbuffers::String *message() const {
    return GetPointer<const ::flatbuffers::String *>(VT_MESSAGE);
  }
  const ::flatbuffers::String *apiImpl() const {
    return GetPointer<const ::flatbuffers::String *>(VT_APIIMPL);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_MESSAGE) &&
           verifier.VerifyString(message()) &&
           VerifyOffset(verifier, VT_APIIMPL) &&
           verifier.VerifyString(apiImpl()) &&
           verifier.EndTable();
  }
};

struct GreetingBuilder {
  typedef Greeting Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_message(::flatbuffers::Offset<::flatbuffers::String> message) {
    fbb_.AddOffset(Greeting::VT_MESSAGE, message);
  }
  void add_apiImpl(::flatbuffers::Offset<::flatbuffers::String> apiImpl) {
    fbb_.AddOffset(Greeting::VT_APIIMPL, apiImpl);
  }
  explicit GreetingBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Greeting> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Greeting>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Greeting> CreateGreeting(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> message = 0,
    ::flatbuffers::Offset<::flatbuffers::String> apiImpl = 0) {
  GreetingBuilder builder_(_fbb);
  builder_.add_apiImpl(apiImpl);
  builder_.add_message(message);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Greeting> CreateGreetingDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *message = nullptr,
    const char *apiImpl = nullptr) {
  auto message__ = message ? _fbb.CreateString(message) : 0;
  auto apiImpl__ = apiImpl ? _fbb.CreateString(apiImpl) : 0;
  return Hello::CreateGreeting(
      _fbb,
      message__,
      apiImpl__);
}

}  // namespace Hello

#endif  // FLATBUFFERS_GENERATED_HELLOTYPES_HELLO_H_
