// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class Greeting {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Greeting {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsGreeting(bb:flatbuffers.ByteBuffer, obj?:Greeting):Greeting {
  return (obj || new Greeting()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsGreeting(bb:flatbuffers.ByteBuffer, obj?:Greeting):Greeting {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Greeting()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

message():string|null
message(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
message(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

apiImpl():string|null
apiImpl(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
apiImpl(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startGreeting(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addMessage(builder:flatbuffers.Builder, messageOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, messageOffset, 0);
}

static addApiImpl(builder:flatbuffers.Builder, apiImplOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, apiImplOffset, 0);
}

static endGreeting(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createGreeting(builder:flatbuffers.Builder, messageOffset:flatbuffers.Offset, apiImplOffset:flatbuffers.Offset):flatbuffers.Offset {
  Greeting.startGreeting(builder);
  Greeting.addMessage(builder, messageOffset);
  Greeting.addApiImpl(builder, apiImplOffset);
  return Greeting.endGreeting(builder);
}
}
