// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;


#[allow(unused_imports, dead_code)]
pub mod hello {


#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_ERROR_CODE: i32 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_ERROR_CODE: i32 = 2;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_ERROR_CODE: [ErrorCode; 3] = [
  ErrorCode::Ok,
  ErrorCode::InvalidArgument,
  ErrorCode::InternalError,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct ErrorCode(pub i32);
#[allow(non_upper_case_globals)]
impl ErrorCode {
  pub const Ok: Self = Self(0);
  pub const InvalidArgument: Self = Self(1);
  pub const InternalError: Self = Self(2);

  pub const ENUM_MIN: i32 = 0;
  pub const ENUM_MAX: i32 = 2;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::Ok,
    Self::InvalidArgument,
    Self::InternalError,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::Ok => Some("Ok"),
      Self::InvalidArgument => Some("InvalidArgument"),
      Self::InternalError => Some("InternalError"),
      _ => None,
    }
  }
}
impl ::core::fmt::Debug for ErrorCode {
  fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> ::flatbuffers::Follow<'a> for ErrorCode {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = unsafe { ::flatbuffers::read_scalar_at::<i32>(buf, loc) };
    Self(b)
  }
}

impl ::flatbuffers::Push for ErrorCode {
    type Output = ErrorCode;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        unsafe { ::flatbuffers::emplace_scalar::<i32>(dst, self.0) };
    }
}

impl ::flatbuffers::EndianScalar for ErrorCode {
  type Scalar = i32;
  #[inline]
  fn to_little_endian(self) -> i32 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: i32) -> Self {
    let b = i32::from_le(v);
    Self(b)
  }
}

impl<'a> ::flatbuffers::Verifiable for ErrorCode {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    i32::run_verifier(v, pos)
  }
}

impl ::flatbuffers::SimpleToVerifyInSlice for ErrorCode {}
pub enum GreetingOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Greeting<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for Greeting<'a> {
  type Inner = Greeting<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> Greeting<'a> {
  pub const VT_MESSAGE: ::flatbuffers::VOffsetT = 4;
  pub const VT_APIIMPL: ::flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    Greeting { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args GreetingArgs<'args>
  ) -> ::flatbuffers::WIPOffset<Greeting<'bldr>> {
    let mut builder = GreetingBuilder::new(_fbb);
    if let Some(x) = args.apiImpl { builder.add_apiImpl(x); }
    if let Some(x) = args.message { builder.add_message(x); }
    builder.finish()
  }


  #[inline]
  pub fn message(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(Greeting::VT_MESSAGE, None)}
  }
  #[inline]
  pub fn apiImpl(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(Greeting::VT_APIIMPL, None)}
  }
}

impl ::flatbuffers::Verifiable for Greeting<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("message", Self::VT_MESSAGE, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("apiImpl", Self::VT_APIIMPL, false)?
     .finish();
    Ok(())
  }
}
pub struct GreetingArgs<'a> {
    pub message: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub apiImpl: Option<::flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for GreetingArgs<'a> {
  #[inline]
  fn default() -> Self {
    GreetingArgs {
      message: None,
      apiImpl: None,
    }
  }
}

pub struct GreetingBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> GreetingBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_message(&mut self, message: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Greeting::VT_MESSAGE, message);
  }
  #[inline]
  pub fn add_apiImpl(&mut self, apiImpl: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Greeting::VT_APIIMPL, apiImpl);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> GreetingBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    GreetingBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<Greeting<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for Greeting<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("Greeting");
      ds.field("message", &self.message());
      ds.field("apiImpl", &self.apiImpl());
      ds.finish()
  }
}
}  // pub mod Hello

