// Generated by xplatter dev on 2026-02-19 17:09:23 PST.
// DO NOT EDIT — this file is regenerated each time xplatter runs.

package main

const (
	HelloErrorCodeOk = 0
	HelloErrorCodeInvalidArgument = 1
	HelloErrorCodeInternalError = 2

)

// HelloGreeting is the Go representation of the Hello.Greeting FlatBuffer type.
type HelloGreeting struct {
	Message string
	ApiImpl string
}

