// Generated by xplatter dev on 2026-02-19 03:07:06 PST.
// This is a scaffold — customize as needed. Regeneration will not overwrite this file.

package main

import "fmt"

// GreeterImpl implements the Greeter interface.
type GreeterImpl struct{}

var _ Greeter = (*GreeterImpl)(nil)

func (s *GreeterImpl) SayHello(name string) (HelloGreeting, error) {
	var message string
	if name == "" {
		message = ""
	} else {
		message = fmt.Sprintf("Hello, %s!", name)
	}
	return HelloGreeting{
		Message: message,
		ApiImpl: "impl-go",
	}, nil
}
