//go:build wasip1

// Generated by xplatter dev on 2026-02-19 17:09:23 PST.
// DO NOT EDIT — this file is regenerated each time xplatter runs.

package main

import (
	"sync"
	"sync/atomic"
	"unsafe"
)

// Memory allocation exports — called by JS binding via malloc/free.
var _wasmAllocs sync.Map

//go:wasmexport malloc
func _wasmMalloc(size uint32) uintptr {
	buf := make([]byte, size)
	ptr := uintptr(unsafe.Pointer(&buf[0]))
	_wasmAllocs.Store(ptr, buf)
	return ptr
}

//go:wasmexport free
func _wasmFree(ptr uintptr) {
	_wasmAllocs.Delete(ptr)
}

// Handle management — maps integer keys to Go interface implementations.
var (
	_wasmHandles sync.Map
	_nextHandle  atomic.Uintptr
)

func _allocHandle(impl interface{}) uintptr {
	key := _nextHandle.Add(1)
	_wasmHandles.Store(key, impl)
	return key
}

func _freeHandle(key uintptr) {
	_wasmHandles.Delete(key)
	// Free any cached WASM strings for this handle
	if val, ok := _wasmStrCache.LoadAndDelete(key); ok {
		for _, ptr := range val.([]uintptr) {
			_wasmFree(ptr)
		}
	}
}

// _cstring reads a null-terminated C string from WASM linear memory.
func _cstring(ptr uintptr) string {
	var n int
	for *(*byte)(unsafe.Pointer(ptr + uintptr(n))) != 0 {
		n++
	}
	return string(unsafe.Slice((*byte)(unsafe.Pointer(ptr)), n))
}

// WASM string cache — maps handle key → []uintptr of allocated strings.
var _wasmStrCache sync.Map

// _wasmCacheStrings allocates null-terminated strings in WASM linear memory
// and caches them for the handle's lifetime (borrowing-only semantics).
func _wasmCacheStrings(handleKey uintptr, ss ...string) []uintptr {
	// Free previous cache
	if val, ok := _wasmStrCache.LoadAndDelete(handleKey); ok {
		for _, ptr := range val.([]uintptr) {
			_wasmFree(ptr)
		}
	}
	result := make([]uintptr, len(ss))
	for i, s := range ss {
		data := []byte(s)
		ptr := _wasmMalloc(uint32(len(data) + 1))
		buf := unsafe.Slice((*byte)(unsafe.Pointer(ptr)), len(data)+1)
		copy(buf, data)
		buf[len(data)] = 0
		result[i] = ptr
	}
	_wasmStrCache.Store(handleKey, result)
	return result
}

// Platform service imports — provided by the JS binding as WASM imports.
//go:wasmimport env hello_xplatter_log_sink
func _platform_log_sink(level int32, tag uintptr, message uintptr)

//go:wasmimport env hello_xplatter_resource_count
func _platform_resource_count() uint32

//go:wasmimport env hello_xplatter_resource_name
func _platform_resource_name(index uint32, buffer uintptr, bufferSize uint32) int32

//go:wasmimport env hello_xplatter_resource_exists
func _platform_resource_exists(name uintptr) int32

//go:wasmimport env hello_xplatter_resource_size
func _platform_resource_size(name uintptr) uint32

//go:wasmimport env hello_xplatter_resource_read
func _platform_resource_read(name uintptr, buffer uintptr, bufferSize uint32) int32

/* lifecycle */

//go:wasmexport hello_xplatter_lifecycle_create_greeter
func hello_xplatter_lifecycle_create_greeter(out_result uintptr) int32 {
	impl := &GreeterImpl{}
	key := _allocHandle(impl)
	*(*uint32)(unsafe.Pointer(out_result)) = uint32(key)
	return 0
}

//go:wasmexport hello_xplatter_lifecycle_destroy_greeter
func hello_xplatter_lifecycle_destroy_greeter(greeter uintptr) {
	_freeHandle(greeter)
}

/* greeter */

//go:wasmexport hello_xplatter_greeter_say_hello
func hello_xplatter_greeter_say_hello(greeter uintptr, name uintptr, out_result uintptr) int32 {
	val, ok := _wasmHandles.Load(greeter)
	if !ok {
		return -1
	}
	impl := val.(Greeter)
	nameGo := _cstring(name)
	result, err := impl.SayHello(nameGo)
	if err != nil {
		return -1
	}
	strPtrs := _wasmCacheStrings(greeter, result.Message, result.ApiImpl)
	*(*uint32)(unsafe.Pointer(out_result + 0)) = uint32(strPtrs[0])
	*(*uint32)(unsafe.Pointer(out_result + 4)) = uint32(strPtrs[1])
	return 0
}

