// Generated by xplatter v0.1.1-8-gf34891c on 2026-02-19 00:02:08 PST.
// DO NOT EDIT — this file is regenerated each time xplatter runs.

import Foundation

public enum HelloErrorCode: Int32, Error {
    case ok = 0
    case invalidArgument = 1
    case outOfMemory = 2
    case notFound = 3
    case internalError = 4
}

public final class Greeter {
    let handle: OpaquePointer

    init(handle: OpaquePointer) {
        self.handle = handle
    }

    deinit {
        hello_xplatter_lifecycle_destroy_greeter(handle)
    }

    public static func createGreeter() throws -> Greeter {
        var result: OpaquePointer?
        let code = hello_xplatter_lifecycle_create_greeter(&result)
        guard code == 0, let ptr = result else {
            throw HelloErrorCode(rawValue: code) ?? HelloErrorCode.internalError
        }
        return Greeter(handle: ptr)
    }

    public func sayHello(name: String) throws -> Hello_Greeting {
        var result: Hello_Greeting = Hello_Greeting()
        return try name.withCString { namePtr in
            let code = hello_xplatter_greeter_say_hello(handle, namePtr, &result)
            guard code == 0 else {
                throw HelloErrorCode(rawValue: code) ?? HelloErrorCode.internalError
            }
            return result
        }
    }

}

