// Auto-generated by xplattergy. DO NOT EDIT.

use std::os::raw::c_char;

#[repr(i32)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum HelloErrorCode {
    Ok = 0,
    InvalidArgument = 1,
    InternalError = 2,
}

#[repr(C)]
#[derive(Debug)]
pub struct HelloGreeting {
    pub message: *const c_char,
    pub apiImpl: *const c_char,
}

