// automatically generated by the FlatBuffers compiler, do not modify
// swiftlint:disable all
// swiftformat:disable all

#if canImport(Common)
import Common
#endif

import FlatBuffers

public enum Hello_ErrorCode: Int32, FlatbuffersVectorInitializable, Enum, Verifiable {
  public typealias T = Int32
  public static var byteSize: Int { return MemoryLayout<Int32>.size }
  public var value: Int32 { return self.rawValue }
  case ok = 0
  case invalidargument = 1
  case internalerror = 2

  public static var max: Hello_ErrorCode { return .internalerror }
  public static var min: Hello_ErrorCode { return .ok }
}


public struct Hello_Greeting: FlatBufferTable, FlatbuffersVectorInitializable, Verifiable {

  static func validateVersion() { FlatBuffersVersion_25_12_19() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case message = 4
    case apiImpl = 6
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var message: String? { let o = _accessor.offset(VTOFFSET.message.v); return o == 0 ? nil : _accessor.string(at: o) }
  public var messageSegmentArray: [UInt8]? { return _accessor.getVector(at: VTOFFSET.message.v) }
  public var apiImpl: String? { let o = _accessor.offset(VTOFFSET.apiImpl.v); return o == 0 ? nil : _accessor.string(at: o) }
  public var apiImplSegmentArray: [UInt8]? { return _accessor.getVector(at: VTOFFSET.apiImpl.v) }
  public static func startGreeting(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 2) }
  public static func add(message: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: message, at: VTOFFSET.message.p) }
  public static func add(apiImpl: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: apiImpl, at: VTOFFSET.apiImpl.p) }
  public static func endGreeting(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createGreeting(
    _ fbb: inout FlatBufferBuilder,
    messageOffset message: Offset = Offset(),
    apiImplOffset apiImpl: Offset = Offset()
  ) -> Offset {
    let __start = Hello_Greeting.startGreeting(&fbb)
    Hello_Greeting.add(message: message, &fbb)
    Hello_Greeting.add(apiImpl: apiImpl, &fbb)
    return Hello_Greeting.endGreeting(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.message.p, fieldName: "message", required: false, type: ForwardOffset<String>.self)
    try _v.visit(field: VTOFFSET.apiImpl.p, fieldName: "apiImpl", required: false, type: ForwardOffset<String>.self)
    _v.finish()
  }
}

