// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum ErrorCode {
  Ok = 0,
  InvalidArgument = 1,
  InternalError = 2
}
