// automatically generated by the FlatBuffers compiler, do not modify

package Hello

@Suppress("unused")
class ErrorCode private constructor() {
    companion object {
        const val Ok: Int = 0
        const val InvalidArgument: Int = 1
        const val InternalError: Int = 2
    }
}
