// automatically generated by the FlatBuffers compiler, do not modify

package Hello

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class Greeting : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : Greeting {
        __init(_i, _bb)
        return this
    }
    val message : String?
        get() {
            val o = __offset(4)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val messageAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(4, 1)
    fun messageInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 4, 1)
    val apiImpl : String?
        get() {
            val o = __offset(6)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val apiImplAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(6, 1)
    fun apiImplInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 6, 1)
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_12_19()
        fun getRootAsGreeting(_bb: ByteBuffer): Greeting = getRootAsGreeting(_bb, Greeting())
        fun getRootAsGreeting(_bb: ByteBuffer, obj: Greeting): Greeting {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createGreeting(builder: FlatBufferBuilder, messageOffset: Int, apiImplOffset: Int) : Int {
            builder.startTable(2)
            addApiImpl(builder, apiImplOffset)
            addMessage(builder, messageOffset)
            return endGreeting(builder)
        }
        fun startGreeting(builder: FlatBufferBuilder) = builder.startTable(2)
        fun addMessage(builder: FlatBufferBuilder, message: Int) = builder.addOffset(0, message, 0)
        fun addApiImpl(builder: FlatBufferBuilder, apiImpl: Int) = builder.addOffset(1, apiImpl, 0)
        fun endGreeting(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
